site_name: Fiori App Usage Report
site_url: https://help.fioriappsusage.org
nav:
    - Learn more: 2020/learn-more.md
    - Installation: 2020/FPS01/inst.md
    - FAQ: 2020/faq.md
    - Case studies: 2020/cases.md
    - Impressum: 2020/impressum.md
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
plugins:
  - macros
  - search
  - social
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
extra:
  analytics:
    provider: google
    property: G-362773498
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/apps-usage-for-sap-fiori-launchpad
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/fioritracker
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xGNzmej4KE
  prod:
    fa:
      name: 'Fiori App Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ''
      R2020FPS01:
        compatibleCoreRel: SPS03      
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        
  