site_name: Fiori App Usage Report
site_description: Speed up project timelines with app insights.
site_url: https://help.fioriappsusage.org
nav:
  - Learn more: 2020/learn-more.md
  - Installation: 2020/FPS01/inst.md
  - FAQ: 2020/faq.md
  - Case studies: 2020/cases.md
  - Impressum: 2020/impressum.md

# Explicitly confirm there is awareness of files not in nav
not_in_nav: |
  /index.md
  /2020/*/
  /2020/diagram.md
  /2020/get-for-free.md
  /2020/success-karma.md
  /2020/success-mining-company.md
  /2020/success-sibelco.md
  /2020/success-stories.md
  /2020/ui5lib-options.md

# Together with --strict flag it allows to crash CI if an error occurs and prevent shipping broken sites
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
    unrecognized_links: warn
theme: 
  name: 'material'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
plugins:
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#0d0d72"  # same color as the corner in the logo.png
  - macros
  - search
copyright: Copyright &copy; 2016 - 2024 Nype
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  analytics:
    provider: google
    property: G-BNGGXFFT1W
  social:
    - icon: fontawesome/solid/building
      link: https://npe.cm/?ref=fioriappsusage
    - icon: fontawesome/brands/github
      link: https://github.com/fioriappsusage
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/showcase/apps-usage-for-sap-fiori-launchpad
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/fioritracker
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xGNzmej4KE
  prod:
    fa:
      name: 'Fiori App Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ''
      R2020FPS01:
        compatibleCoreRel: SPS03      
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        
  