site_name: Fiori App Usage Report
site_description: Speed up project timelines with app insights.
site_url: https://help.fioriappsusage.org
nav:
  - Case studies: 2020/cases.md
  - Use cases:
    - 2020/FPS01/use-cases/index.md
  - Explore Details: 
    - 2020/fiori-apps-usage-details.md
    - Features: 2020/FPS01/features/index.md
    - Architecture: 2020/arch/architecture.md
    - Configuration: 2020/FPS01/conf.md
    - Installation: https://fioritracker.org/inst/
    - FAQ: faq.md
  - Impressum: impressum.md

# Explicitly confirm there is awareness of files not in nav
not_in_nav: |
  /index.md
  /contact.md
  /contact-success.md
  /free-offer.md
  /offer.md
  /2020/*/
  /2020/diagram.md
  /2020/get-for-free.md
  /2020/success-karma.md
  /2020/success-mining-company.md
  /2020/success-sibelco.md
  /2020/success-stories.md
  /2020/ui5lib-options.md
  /2020/free-cases.md
  /2020/faq.md

# Together with --strict flag it allows to crash CI if an error occurs and prevent shipping broken sites
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn  # If needed change to 'relative_to_docs'
    unrecognized_links: warn
theme: 
  name: nype
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  custom_dir: overrides
  features:
    - content.tooltips
    - navigation.tabs
  nype_config:
    contact_form_action_hex: 6148523063484d364c79396d62334a74637935316269317a6447463061574d75593239744c325a76636d317a4c325a6c4d6d51774e5745315a6d4d795a6d4d3559574a6a595755305a4751794d7a6b7a4d54497a4e5456684e5751305954686d4d32553d
    contact_form_email_hex: 5047456761484a6c5a6a306962574670624852764f6d5a6864554275634755755932302f63335669616d566a6444314761573979615342426348416756584e685a325536494334754c69492b5a6d4631514735775a53356a625477765954343d
plugins:
  - blog:
      archive: false
      blog_dir: 2020/FPS01/features
      post_url_format: "{slug}"
      post_readtime: false
      pagination: false
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#0d0d72"  # same color as the corner in the logo.png
  - macros:
      on_error_fail: !ENV [CI, false]
  - search
  - minify:
      enabled: !ENV [CI, false]
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - sap_icons
  - server_redirects:
      raw_redirects:
        /2020/FPS01/recexp/?$: /2020/FPS01/features/recexp/
        /2020/FPS01/app-ids/?$: /2020/FPS01/features/app-ids/
        /2020/FPS01/cleaning/?$: /2020/FPS01/features/cleaning/
        /2020/FPS01/filtering/?$: /2020/FPS01/features/filtering/
        /2020/FPS01/ft-core-relation-app-usage/?$: /2020/FPS01/features/ft-core-relation-app-usage/
        /2020/inst(.*): https://fioritracker.org/inst$1
        /2020/impressum/: /impressum/
copyright: Copyright &copy; 2016 - 2024 Nype
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
extra:
  analytics:
    provider: google
    property: G-BNGGXFFT1W
  social:
    - icon: ext/nype-logo
      link: https://npe.cm/?ref=fioriappsusage
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/showcase/apps-usage-for-sap-fiori-launchpad
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/fioritracker
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xGNzmej4KE
  prod:
    fa:
      name: 'Fiori App Usage'
      main: '2020'
      latestrel: 'FPS01'
      cen: 'X'
      man: ''
      R2020FPS01:
        compatibleCoreRel: SPS03      
        compatibleCoreLink: 'https://help.fioritracker.org/V2020/core/SPS03/main/'
        
  